language: perl
perl:
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
